version: "3"

services:
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - postgres
